# Generated by Django 5.2.3 on 2025-06-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['module_order'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='order',
            new_name='module_order',
        ),
    ]
