# Generated by Django 5.2.3 on 2025-06-11 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('link', 'Link'), ('other', 'Other')], default='document', max_length=10)),
                ('url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.module')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'material',
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_materials', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='content.material')),
            ],
            options={
                'verbose_name': 'Material Favorito',
                'verbose_name_plural': 'Materiales Favoritos',
                'db_table': 'favorite_material',
                'unique_together': {('user', 'material')},
            },
        ),
    ]
