# Generated by Django 5.2.3 on 2025-06-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='url',
            new_name='resource_url',
        ),
    ]
