# Generated by Django 5.2.3 on 2025-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_url_material_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='text_plain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
