# Generated by Django 5.2.3 on 2025-06-30 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_material_text_plain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('summary', 'Resumen'), ('flashcards', 'Flashcards')], max_length=20)),
                ('output_format', models.CharField(choices=[('text', 'Texto'), ('json', 'JSON')], max_length=10)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='content.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenido Generado',
                'verbose_name_plural': 'Contenidos Generados',
                'db_table': 'generated_content',
                'ordering': ['-creation_date'],
            },
        ),
    ]
