# Generated by Django 5.2.3 on 2025-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late'), ('empty', 'Empty')], default='pending', max_length=10),
        ),
    ]
